routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => ['auth']], function() {

    Route::get('/singin',    ['as'=>'singin', 'uses'=>'GeneralController@singin']);

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
    });

    Route::group(['prefix' => 'documents', 'namespace' => 'Documents',], function() {

        Route::group(['middleware' => ['isAdmin']], function() {
            Route::group(['prefix' => 'racts'], function() {
                Route::group(['prefix' => 'ractversions'], function() {
                    Route::get('rmeta/{id}',    ['as'=>'ractversions.rmeta', 'uses'=>'RactversionController@rmeta']);
                    Route::get('jcontent/{id}',    ['as'=>'ractversions.jcontent', 'uses'=>'RactversionController@jcontent']);
                    Route::get('rwork/{id}',    ['as'=>'ractversions.rwork', 'uses'=>'RactversionController@rwork']);
                });
                Route::get('rmeta/{id}',    ['as'=>'racts.rmeta', 'uses'=>'RactController@rmeta']);
                Route::get('repllink/{id}',    ['as'=>'racts.repllink', 'uses'=>'RactController@repllink']);
                Route::resource('ractversions', 'RactversionController');
            });
            Route::resource('racts', 'RactController');
        });

        Route::group(['middleware' => ['isActs']], function() {
            Route::group(['prefix' => 'acts'], function() {
                Route::resource('actversions', 'ActversionController');
                Route::group(['prefix' => 'comments'], function() {
                    Route::resource('commentlocals', 'CommentlocalController');
                });
                Route::resource('comments', 'CommentController');
                Route::get('trash',    ['as'=>'act-trash', 'uses'=>'ActController@trash']);
            });
            Route::resource('acts', 'ActController');
        });

        Route::group(['prefix' => 'news'], function() {
            Route::get('trash',    ['as'=>'news-trash', 'uses'=>'NewsController@trash']);
        });
        Route::resource('news', 'NewsController');

        Route::resource('jurs', 'JurController');
        Route::resource('monographs', 'MonographController');
        Route::group(['prefix' => 'monographs'], function() {
            Route::resource('mfragments', 'MfragmentController');
        });

        Route::group(['middleware' => ['isPubs']], function() {
            Route::group(['prefix' => 'publications'], function() {
                Route::get('trash',    ['as'=>'publication-trash', 'uses'=>'PublicationController@trash']);
            });
            Route::resource('publications', 'PublicationController');
        });
    });

    Route::group(['prefix' => 'vocabularies', 'namespace' => 'Vocabularies'], function() {
        Route::resource('regions', 'RegionController');

        Route::resource('publishers', 'PublisherController');
        Route::resource('types', 'TypeController');
        Route::resource('sources', 'SourceController');
        Route::resource('asubacts', 'AsubactController');
        Route::resource('akeywords', 'AkeywordController');

        Route::resource('ncats', 'NcatController');

        Route::resource('justice-kind', 'JusticeKindController');
        Route::resource('judgment-code', 'JudgmentCodeController');
        Route::resource('court-code', 'CourtCodeController');
        Route::resource('cause-category', 'CauseCategoryController');
        Route::resource('instances', 'InstanceController');
        Route::resource('judges', 'JudgeController');

        Route::resource('mauthors', 'MauthorController');
        Route::resource('mnodetypes', 'MnodetypeController');

        Route::resource('pauthors', 'PauthorController');
        Route::resource('pauthorroles', 'PauthorroleController');
        Route::resource('pglosstypes', 'PglosstypeController');
        Route::resource('psources', 'PsourceController');
        Route::resource('pdocsubtypes', 'PdocsubtypeController');

        Route::resource('cauthors', 'CauthorController');
        Route::resource('cauthorroles', 'CauthorroleController');
        Route::resource('csources', 'CsourceController');
        Route::resource('cdocsubtypes', 'CdocsubtypeController');
    });

    Route::group(['prefix' => 'tools', 'middleware' => ['isAdmin']], function() {

        Route::resource('exportdatas', 'ExportdataController');
        Route::resource('exportvocs',  'ExportvocController');
        Route::resource('exportvocmodels', 'ExportvocmodelController');
        Route::resource('blocks', 'BlockController');
        
        Route::post('/export',    ['as'=>'export', 'uses'=>'ExportController@index']);
        Route::post('/exportvoc', ['as'=>'exportvoc', 'uses'=>'ExportController@exportvoc']);

        Route::resource('logactions', 'LogactionController');
        Route::resource('logs', 'LogController');

        Route::get('/tools',       ['as'=>'tools', 'uses'=>'GeneralController@tools']);
        Route::get('/reincrement', ['as'=>'reincrement', 'uses'=>'ToolController@reincrement']);
        Route::get('/lexinform',   ['as'=>'lexinform', 'uses'=>'ToolController@lexinform']);
        Route::get('/blocks-map',  ['as'=>'blocks-map', 'uses'=>'GeneralController@create_blocks_map']);
        Route::get('/relations',   ['as'=>'relations', 'uses'=>'ToolController@relations']);
        # страница для тестов
        Route::get('/dev',   ['as'=>'dev', 'uses'=>'ToolController@dev']);
        Route::get('/link',  ['as'=>'link','uses'=>'ToolController@link']);
        Route::get('/toc',   ['as'=>'toc', 'uses'=>'ToolController@toc']);
        # страница для RADA BOT
        Route::get('/radabot',   ['as'=>'radabot', 'uses'=>'ToolController@radabot']);
        Route::resource('ractions', 'RactionController', ['except' => 'show']);

        Route::get('rbotstatuses/datatable',    ['as'=>'rbotstatuses.datatable','uses'=>'RbotstatusController@datatable']);
        Route::post('rbotstatuses/datatable',    ['as'=>'rbotstatuses.datatable','uses'=>'RbotstatusController@datatable']);
        Route::resource('rbotstatuses', 'RbotstatusController', ['except' => 'show']);
    });

    Route::match(['get', 'post'],'/account',    ['as'=>'account', 'uses'=>'GeneralController@account']);

});

Route::post( '/logout', ['as'=>'logout', 'uses'=>'GeneralController@logout']);

Route::get('/',    ['as'=>'home', 'uses'=>'GeneralController@index']);

app/Http/Controllers/LogactionController.php
<?php

namespace App\Http\Controllers;

use App\Logaction;
use App\Http\Requests\StoreLogactionRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LogactionController extends Controller
{
    public function __construct() {
        parent::__construct();
        $this->data['icon'] = 'icon-books';
        $this->data['title'] = trans('cms.voc-logactions');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => route('logactions.index')]);
    }


    public function index(Request $request)
    {
        $where = [];
            if ($request->sid)  { $where[]=['id','=', $request->sid]; }
            if ($request->sname)  { $where[]=['name','like', '%'.$request->sname.'%']; }
        $models = Logaction::where($where)->orderby('id')->paginate(20);
        return view('Tools.Logaction.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
                'data' => $this->data,
            ]);
    }


    public function create()
    {
        $this->data['subtitle'] = trans('cms.title-create');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        return view('Tools.Logaction.create', ['data'=>$this->data]);
    }


    public function store(StoreLogactionRequest $request)
    {
        $model = new Logaction;
        $model->id = $request->id;
        $model->name = $request->name;
        $model->save();
        
        return redirect()->route('logactions.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function edit($id)
    {
        $this->data['subtitle'] = trans('cms.title-edit');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        $model = Logaction::findOrFail($id);
        return view('Tools.Logaction.edit', [
                'model'=>$model,
                'data'=>$this->data,
            ]);
    }

    public function update(StoreLogactionRequest $request, $id)
    {
        $model = Logaction::findOrFail($id);
        $model->id = $request->id;
        $model->name = $request->name;
        $model->save();
        return redirect()->route('logactions.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Logaction::findOrFail($id);
        $model->delete();
        return redirect(route('logactions.index'))
            ->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

resources/views/Tools/Logaction/create.blade.php
@extends('layouts.limitless-layout')

@section('content')

{{ Form::open(array('url' => 'tools/logactions')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('cms.title-parameters') }}</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ Form::label('id', trans('cms.column-key'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('id', null, array('class' => 'form-control'. ($errors->has('id') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('id'))
                        @foreach ($errors->get('id') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
                <div class="form-group">
                    {{ Form::label('name', trans('cms.column-name'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('name', null, array('class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('name'))
                        @foreach ($errors->get('name') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">{{ trans('cms.title-navigation') }}</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="{{ trans('cms.btn-save') }}"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('logactions.index') }}" class="btn btn-danger btn-block w-50" title="{{ trans('cms.btn-exit') }}"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

resources/views/Tools/Logaction/edit.blade.php
@extends('layouts.limitless-layout')

@section('content')

{{ Form::model($model, array('route' => array('logactions.update', $model->id), 'method' => 'PUT')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('cms.title-parameters') }}</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ Form::label('id', trans('cms.column-key'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('id', null, array('class' => 'form-control'. ($errors->has('id') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('id'))
                        @foreach ($errors->get('id') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
                <div class="form-group">
                    {{ Form::label('name', trans('cms.column-name'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('name', null, array('class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('name'))
                        @foreach ($errors->get('name') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">{{ trans('cms.title-navigation') }}</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="{{ trans('cms.btn-save') }}"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('logactions.index') }}" class="btn btn-danger btn-block w-50" title="{{ trans('cms.btn-exit') }}"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

resources/views/Tools/Logaction/index.blade.php
@extends('layouts.limitless-layout')

@section('content')
<div class="card mb-3">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">{{ $data['title'] OR ''}}</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>{{trans('cms.column-key')}}</th>
                        <th>{{trans('cms.column-name')}}</th>
                        <th>{{trans('cms.column-actions')}}</th>
                    </tr>
                    <tr class="filter-line">
                        {!! Form::open(['method' => 'GET', 'route' => ['logactions.index'], 'id'=>'filter-form' ]) !!}
                            <th>{{ Form::text('sid', isset($_GET['sid']) ? $_GET['sid'] : null, array('class' => 'form-control form-control-sm')) }}</th>
                            <th>{{ Form::text('sname', isset($_GET['sname']) ? $_GET['sname'] : null, array('class' => 'form-control form-control-sm')) }}</th>
                            <th>
                                <div class="list-icons">
                                    <a href="#" class="list-icons-item text-primary-600 btn-filter" title="{{ trans('cms.btn-filter') }}"><i class="icon-filter3"></i></a>
                                </div>
                            </th>
                        {!! Form::close() !!}
                    </tr>
                </thead>
                <tbody>
                    @foreach ($models as $model)
                    <tr>
                        <td class="text-center">{{ $model->id }}</td>
                        <td>{{ $model->name }}</td>
                        <td class="text-center">
                            <div class="list-icons">
                                <a href="{{ route('logactions.edit', $model->id) }}" class="list-icons-item" title="{{ trans('cms.btn-edit') }}"><i class="icon-pencil7"></i></a>
                                <a href="{{route('logactions.destroy', $model->id)}}" class="list-icons-item text-danger-600 btn-remove" title="{{ trans('cms.btn-remove') }}" data-toggle="modal" data-target="#modal_theme_danger"><i class="icon-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="d-flex mt-3">
            <a href="{{ route('logactions.create') }}" class="btn btn-success" title="{{ trans('cms.btn-create') }}"><i class="icon-file-plus"></i></a>
            {{ $models->appends($pagination_add)->links() }}
        </div>
    </div>
</div>

@endsection