routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => ['auth']], function() {

    Route::get('/singin',    ['as'=>'singin', 'uses'=>'GeneralController@singin']);

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
    });

    Route::group(['prefix' => 'documents', 'namespace' => 'Documents',], function() {

        Route::group(['middleware' => ['isAdmin']], function() {
            Route::group(['prefix' => 'racts'], function() {
                Route::group(['prefix' => 'ractversions'], function() {
                    Route::get('rmeta/{id}',    ['as'=>'ractversions.rmeta', 'uses'=>'RactversionController@rmeta']);
                    Route::get('jcontent/{id}',    ['as'=>'ractversions.jcontent', 'uses'=>'RactversionController@jcontent']);
                    Route::get('rwork/{id}',    ['as'=>'ractversions.rwork', 'uses'=>'RactversionController@rwork']);
                });
                Route::get('rmeta/{id}',    ['as'=>'racts.rmeta', 'uses'=>'RactController@rmeta']);
                Route::get('repllink/{id}',    ['as'=>'racts.repllink', 'uses'=>'RactController@repllink']);
                Route::resource('ractversions', 'RactversionController');
            });
            Route::resource('racts', 'RactController');
        });

        Route::group(['middleware' => ['isActs']], function() {
            Route::group(['prefix' => 'acts'], function() {
                Route::resource('actversions', 'ActversionController');
                Route::group(['prefix' => 'comments'], function() {
                    Route::resource('commentlocals', 'CommentlocalController');
                });
                Route::resource('comments', 'CommentController');
                Route::get('trash',    ['as'=>'act-trash', 'uses'=>'ActController@trash']);
            });
            Route::resource('acts', 'ActController');
        });

        Route::group(['prefix' => 'news'], function() {
            Route::get('trash',    ['as'=>'news-trash', 'uses'=>'NewsController@trash']);
        });
        Route::resource('news', 'NewsController');

        Route::resource('jurs', 'JurController');
        Route::resource('monographs', 'MonographController');
        Route::group(['prefix' => 'monographs'], function() {
            Route::resource('mfragments', 'MfragmentController');
        });

        Route::group(['middleware' => ['isPubs']], function() {
            Route::group(['prefix' => 'publications'], function() {
                Route::get('trash',    ['as'=>'publication-trash', 'uses'=>'PublicationController@trash']);
            });
            Route::resource('publications', 'PublicationController');
        });
    });

    Route::group(['prefix' => 'vocabularies', 'namespace' => 'Vocabularies'], function() {
        Route::resource('regions', 'RegionController');

        Route::resource('publishers', 'PublisherController');
        Route::resource('types', 'TypeController');
        Route::resource('sources', 'SourceController');
        Route::resource('asubacts', 'AsubactController');
        Route::resource('akeywords', 'AkeywordController');

        Route::resource('ncats', 'NcatController');

        Route::resource('justice-kind', 'JusticeKindController');
        Route::resource('judgment-code', 'JudgmentCodeController');
        Route::resource('court-code', 'CourtCodeController');
        Route::resource('cause-category', 'CauseCategoryController');
        Route::resource('instances', 'InstanceController');
        Route::resource('judges', 'JudgeController');

        Route::resource('mauthors', 'MauthorController');
        Route::resource('mnodetypes', 'MnodetypeController');

        Route::resource('pauthors', 'PauthorController');
        Route::resource('pauthorroles', 'PauthorroleController');
        Route::resource('pglosstypes', 'PglosstypeController');
        Route::resource('psources', 'PsourceController');
        Route::resource('pdocsubtypes', 'PdocsubtypeController');

        Route::resource('cauthors', 'CauthorController');
        Route::resource('cauthorroles', 'CauthorroleController');
        Route::resource('csources', 'CsourceController');
        Route::resource('cdocsubtypes', 'CdocsubtypeController');
    });

    Route::group(['prefix' => 'tools', 'middleware' => ['isAdmin']], function() {

        Route::resource('exportdatas', 'ExportdataController');
        Route::resource('exportvocs',  'ExportvocController');
        Route::resource('exportvocmodels', 'ExportvocmodelController');
        Route::resource('blocks', 'BlockController');
        
        Route::post('/export',    ['as'=>'export', 'uses'=>'ExportController@index']);
        Route::post('/exportvoc', ['as'=>'exportvoc', 'uses'=>'ExportController@exportvoc']);

        Route::resource('logactions', 'LogactionController');
        Route::resource('logs', 'LogController');

        Route::get('/tools',       ['as'=>'tools', 'uses'=>'GeneralController@tools']);
        Route::get('/reincrement', ['as'=>'reincrement', 'uses'=>'ToolController@reincrement']);
        Route::get('/lexinform',   ['as'=>'lexinform', 'uses'=>'ToolController@lexinform']);
        Route::get('/blocks-map',  ['as'=>'blocks-map', 'uses'=>'GeneralController@create_blocks_map']);
        Route::get('/relations',   ['as'=>'relations', 'uses'=>'ToolController@relations']);
        # страница для тестов
        Route::get('/dev',   ['as'=>'dev', 'uses'=>'ToolController@dev']);
        Route::get('/link',  ['as'=>'link','uses'=>'ToolController@link']);
        Route::get('/toc',   ['as'=>'toc', 'uses'=>'ToolController@toc']);
        # страница для RADA BOT
        Route::get('/radabot',   ['as'=>'radabot', 'uses'=>'ToolController@radabot']);
        Route::resource('ractions', 'RactionController', ['except' => 'show']);

        Route::get('rbotstatuses/datatable',    ['as'=>'rbotstatuses.datatable','uses'=>'RbotstatusController@datatable']);
        Route::post('rbotstatuses/datatable',    ['as'=>'rbotstatuses.datatable','uses'=>'RbotstatusController@datatable']);
        Route::resource('rbotstatuses', 'RbotstatusController', ['except' => 'show']);
    });

    Route::match(['get', 'post'],'/account',    ['as'=>'account', 'uses'=>'GeneralController@account']);

});

Route::post( '/logout', ['as'=>'logout', 'uses'=>'GeneralController@logout']);

Route::get('/',    ['as'=>'home', 'uses'=>'GeneralController@index']);

app/Http/Controllers/Vocabularies/AkeywordController.php
<?php

namespace App\Http\Controllers\Vocabularies;

use App\Akeyword;
use App\Http\Requests\StoreAkeywordRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AkeywordController extends Controller
{
    public function __construct() {
        parent::__construct();
        $this->data['icon'] = 'icon-books';
        $this->data['title'] = trans('cms.voc-akeyword');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => route('akeywords.index')]);
    }

    public function index(Request $request)
    {
        $models = Akeyword::orderby('id')->paginate(20);
        return view('Vocabularies.Akeyword.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
                'data' => $this->data,
            ]);
    }

    public function create()
    {
        $this->data['subtitle'] = trans('cms.title-create');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        return view('Vocabularies.Akeyword.create', [
                'data' => $this->data,
            ]);
    }

    public function store(StoreAkeywordRequest $request)
    {
        $model = new Akeyword;
        $model->name = $request->name;
        $model->save();
        Auth::user()->log($request->ip(), 1141, $model->id);
        return redirect()->route('akeywords.index')
            ->with('flash_message', 'Ключевое слово ' . $model->name . ' создано');
    }

    public function edit($id)
    {
        $this->data['subtitle'] = trans('cms.title-edit');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        $model = Akeyword::findOrFail($id);
        return view('Vocabularies.Akeyword.edit', [
                'model'=>$model,
                'data' => $this->data,
            ]);
    }

    public function update(StoreAkeywordRequest $request, $id)
    {
        $model = Akeyword::findOrFail($id);
        $model->name = $request->name;
        $model->save();
        Auth::user()->log($request->ip(), 1142, $model->id);
        return redirect()->route('akeywords.index')
            ->with('flash_message', 'Ключевое слово ' . $model->name . ' изменено');
    }

    public function destroy(Request $request, $id)
    {
        $model = Akeyword::findOrFail($id);
        $model->delete();
        Auth::user()->log($request->ip(), 1143, $model->id);
        return redirect(route('akeywords.index'))->with('error_message', 'Ключевое слово ' . $model->name . ' удалено');
    }

}

app/Http/Controllers/Vocabularies/AsubactController.php
<?php

namespace App\Http\Controllers\Vocabularies;

use App\Asubact;
use App\Http\Requests\StoreAsubactRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AsubactController extends Controller
{
    public function __construct() {
        parent::__construct();
        $this->data['icon'] = 'icon-books';
        $this->data['title'] = trans('cms.voc-asubact');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => route('asubacts.index')]);
    }


    public function index(Request $request)
    {
        $models = Asubact::orderby('id')->paginate(20);
        return view('Vocabularies.Asubact.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
                'data' => $this->data,
            ]);
    }

    public function create()
    {
        $this->data['subtitle'] = trans('cms.title-create');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        return view('Vocabularies.Asubact.create', [
                'data' => $this->data,
            ]);
    }

    public function store(StoreAsubactRequest $request)
    {
        $model = new Asubact;
        $model->name = $request->name;
        $model->save();
        Auth::user()->log($request->ip(), 1131, $model->id);
        return redirect()->route('asubacts.index')
            ->with('flash_message', 'Подтип актов ' . $model->name . ' создан');
    }

    public function edit($id)
    {
        $this->data['subtitle'] = trans('cms.title-edit');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        $model = Asubact::findOrFail($id);
        return view('Vocabularies.Asubact.edit', [
                'model'=>$model,
                'data' => $this->data,
            ]);
    }

    public function update(StoreAsubactRequest $request, $id)
    {
        $model = Asubact::findOrFail($id);
        $model->name = $request->name;
        $model->save();
        Auth::user()->log($request->ip(), 1132, $model->id);
        return redirect()->route('asubacts.index')
            ->with('flash_message', 'Подтип актов ' . $model->name . ' изменен');
    }

    public function destroy(Request $request, $id)
    {
        $model = Asubact::findOrFail($id);
        $model->delete();
        Auth::user()->log($request->ip(), 1133, $model->id);
        return redirect(route('asubacts.index'))->with('error_message', 'Подтип актов ' . $model->name . ' удален');
    }

}

app/Http/Controllers/Vocabularies/CauseCategoryController.php
<?php

namespace App\Http\Controllers\Vocabularies;

use App\CauseCategory;
use App\Http\Requests\StoreVariantRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CauseCategoryController extends Controller
{
    public function __construct() {
        parent::__construct();
    }

    public function index(Request $request)
    {
        $models = CauseCategory::paginate(10);
        return view('Vocabularies.CauseCategory.index', [
                'title' => 'Vocabularies',
                'models' => $models,
            ]);
    }

    public function create()
    {
        $title = trans('main.create-variant');
        array_push($this->breadcrumbs , ["title" => $title,"url" => "#"]);
        return view('Vocabularies.CauseCategory.create', ['title'=>$title, 'breadcrumbs' => $this->breadcrumbs]);
    }

    public function store(StoreVariantRequest $request)
    {
        $variant = new Variant;
        $variant->name = $request->name;
        $variant->save();
        $variant->sync_answers(json_decode($request['answers']));
        
        return redirect()->route('CauseCategory.index')
            ->with('flash_message', trans('messages.appended', ['item'=>trans('main.variant'), 'name' => $variant->name]));
    }

    public function edit($id)
    {
        $title = trans('main.edit-variant');
        array_push($this->breadcrumbs , ["title" => $title,"url" => "#"]);
        $variant = Variant::findOrFail($id);
        return view('Vocabularies.CauseCategory.edit', [
                'title'=>$title,
                'variant'=>$variant,
                'breadcrumbs' => $this->breadcrumbs
            ]);
    }

    public function update(StoreVariantRequest $request, $id)
    {
        $variant = Variant::findOrFail($id);
        $variant->name = $request['name'];
        $variant->save();
        $variant->sync_answers(json_decode($request['answers']));
        return redirect()->route('CauseCategory.index')
            ->with('flash_message', trans('messages.edited', ['item'=>trans('main.variant'), 'name' => $variant->name]));
    }

    public function destroy(Request $request, $id)
    {
        $variant = Variant::findOrFail($id);
        $variant->delete();
        return redirect(route('CauseCategory.index'))->with('error_message', trans('messages.deleted', ['item'=>trans('main.variant'), 'name' => $variant->name]));
    }

}

app/Http/Controllers/Vocabularies/CauthorController.php
<?php

namespace App\Http\Controllers\Vocabularies;

use App\Cauthor;
use App\Cauthorrole;
use App\Http\Requests\StoreCauthorRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CauthorController extends Controller
{
    public function __construct() {
        parent::__construct();
        $this->data['icon'] = 'icon-books';
        $this->data['title'] = trans('cms.voc-cauthor');
        array_push($this->data['breadcrumbs'] , ["title" => trans('cms.doc-act'),"url" => route('acts.index')]);
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => route('cauthors.index')]);
    }

    public function index(Request $request)
    {
        $models = Cauthor::orderby('id')->paginate(20);
        return view('Vocabularies.Cauthor.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
                'data' => $this->data,
            ]);
    }

    public function create()
    {
        array_push($this->data['breadcrumbs'] , ["title" => trans('cms.title-create') ,"url" => "#"]);
        $cauthorroles = Cauthorrole::get();
        return view('Vocabularies.Cauthor.create', [
                'cauthorroles' => $cauthorroles,
                'data' => $this->data,
            ]);
    }

    public function store(StoreCauthorRequest $request)
    {
        $model = new Cauthor;
        $model->name = $request->name;
        $model->save();
        $model->cauthorroles()->sync($request->cauthorroles);
        Auth::user()->log($request->ip(), 6101, $model->id);
        return redirect()->route('cauthors.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function edit($id)
    {
        array_push($this->data['breadcrumbs'] , ["title" => trans('cms.title-edit') ,"url" => "#"]);
        $model = Cauthor::findOrFail($id);
        $cauthorroles = Cauthorrole::get();
        return view('Vocabularies.Cauthor.edit', [
                'model'=>$model,
                'cauthorroles' => $cauthorroles,
                'data' => $this->data,
            ]);
    }

    public function update(StoreCauthorRequest $request, $id)
    {
        $model = Cauthor::findOrFail($id);
        $model->name = $request->name;
        $model->save();
        $model->cauthorroles()->sync($request->cauthorroles);
        Auth::user()->log($request->ip(), 6102, $model->id);
        return redirect()->route('cauthors.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Cauthor::findOrFail($id);
        $model->delete();
        Auth::user()->log($request->ip(), 6103, $model->id);
        return redirect(route('cauthors.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

resources/views/Vocabularies/Ncat/create.blade.php
@extends('layouts.limitless-layout')

@section('content')

{{ Form::open(array('url' => 'vocabularies/ncats')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('cms.title-parameters') }}</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ Form::label('id', trans('cms.column-key'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('id', null, array('class' => 'form-control'. ($errors->has('id') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('id'))
                        @foreach ($errors->get('id') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
                <div class="form-group">
                    {{ Form::label('name', trans('cms.column-name'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('name', null, array('class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('name'))
                        @foreach ($errors->get('name') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">{{ trans('cms.title-navigation') }}</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="{{ trans('cms.btn-save') }}"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('ncats.index') }}" class="btn btn-danger btn-block w-50" title="{{ trans('cms.btn-exit') }}"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

resources/views/Vocabularies/Ncat/edit.blade.php
@extends('layouts.limitless-layout')

@section('content')

{{ Form::model($model, array('route' => array('ncats.update', $model->id), 'method' => 'PUT')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <div class="order-2 order-md-1 w-100">
        <div class="card mb-3">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{ trans('cms.title-parameters') }}</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    {{ Form::label('id', trans('cms.column-key'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('id', null, array('class' => 'form-control'. ($errors->has('id') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('id'))
                        @foreach ($errors->get('id') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
                <div class="form-group">
                    {{ Form::label('name', trans('cms.column-name'), ['class'=>'small text-muted font-italic']) }}
                    {{ Form::text('name', null, array('class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : '' ))) }}
                    @if($errors->has('name'))
                        @foreach ($errors->get('name') as $message)
                            <div class="invalid-feedback">{{ $message }}</div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">{{ trans('cms.title-navigation') }}</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group w-100">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="{{ trans('cms.btn-save') }}"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('ncats.index') }}" class="btn btn-danger btn-block w-50" title="{{ trans('cms.btn-exit') }}"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

resources/views/Vocabularies/Ncat/index.blade.php
@extends('layouts.limitless-layout')

@section('content')
<div class="card mb-3">
    <div class="card-header header-elements-inline">
        <h5 class="card-title">{{ $data['title'] OR ''}}</h5>
        <div class="header-elements">
            <div class="list-icons">
                <a class="list-icons-item" data-action="collapse"></a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>{{trans('cms.column-key')}}</th>
                        <th>{{trans('cms.column-name')}}</th>
                        <th>{{trans('cms.column-actions')}}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($models as $model)
                    <tr>
                        <td class="text-center">{{ $model->id }}</td>
                        <td>{{ $model->name }}</td>
                        <td class="text-center">
                            <div class="list-icons">
                                <a href="{{ route('ncats.edit', $model->id) }}" class="list-icons-item" title="{{ trans('cms.btn-edit') }}"><i class="icon-pencil7"></i></a>
                                @can('admin')
                                    <a href="{{route('ncats.destroy', $model->id)}}" class="list-icons-item text-danger-600 btn-remove" title="{{ trans('cms.btn-remove') }}" data-toggle="modal" data-target="#modal_theme_danger"><i class="icon-trash"></i></a>
                                @endcan
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="d-flex mt-3">
            <a href="{{ route('ncats.create') }}" class="btn btn-success" title="{{ trans('cms.btn-create') }}"><i class="icon-file-plus"></i></a>
            {{ $models->appends($pagination_add)->links() }}
        </div>
    </div>
</div>

@endsection