routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::group(['middleware' => ['auth']], function() {

    Route::get('/singin',    ['as'=>'singin', 'uses'=>'GeneralController@singin']);

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController', ['except' => 'show']);
        Route::resource('permissions', 'PermissionController', ['except' => 'show']);
    });

    Route::group(['prefix' => 'documents', 'namespace' => 'Documents',], function() {

        Route::group(['middleware' => ['isAdmin']], function() {
            Route::group(['prefix' => 'racts'], function() {
                Route::group(['prefix' => 'ractversions'], function() {
                    Route::get('rmeta/{id}',    ['as'=>'ractversions.rmeta', 'uses'=>'RactversionController@rmeta']);
                    Route::get('jcontent/{id}',    ['as'=>'ractversions.jcontent', 'uses'=>'RactversionController@jcontent']);
                    Route::get('rwork/{id}',    ['as'=>'ractversions.rwork', 'uses'=>'RactversionController@rwork']);
                });
                Route::get('rmeta/{id}',    ['as'=>'racts.rmeta', 'uses'=>'RactController@rmeta']);
                Route::get('repllink/{id}',    ['as'=>'racts.repllink', 'uses'=>'RactController@repllink']);
                Route::resource('ractversions', 'RactversionController');
            });
            Route::resource('racts', 'RactController');
        });

        Route::group(['middleware' => ['isActs']], function() {
            Route::group(['prefix' => 'acts'], function() {
                Route::resource('actversions', 'ActversionController');
                Route::group(['prefix' => 'comments'], function() {
                    Route::resource('commentlocals', 'CommentlocalController');
                });
                Route::resource('comments', 'CommentController');
                Route::get('trash',    ['as'=>'act-trash', 'uses'=>'ActController@trash']);
            });
            Route::resource('acts', 'ActController');
        });

        Route::group(['prefix' => 'news'], function() {
            Route::get('trash',    ['as'=>'news-trash', 'uses'=>'NewsController@trash']);
        });
        Route::resource('news', 'NewsController');

        Route::resource('jurs', 'JurController');
        Route::resource('monographs', 'MonographController');
        Route::group(['prefix' => 'monographs'], function() {
            Route::resource('mfragments', 'MfragmentController');
        });

        Route::group(['middleware' => ['isPubs']], function() {
            Route::group(['prefix' => 'publications'], function() {
                Route::get('trash',    ['as'=>'publication-trash', 'uses'=>'PublicationController@trash']);
            });
            Route::resource('publications', 'PublicationController');
        });
    });

    Route::group(['prefix' => 'vocabularies', 'namespace' => 'Vocabularies'], function() {
        Route::resource('regions', 'RegionController');

        Route::resource('publishers', 'PublisherController');
        Route::resource('types', 'TypeController');
        Route::resource('sources', 'SourceController');
        Route::resource('asubacts', 'AsubactController');
        Route::resource('akeywords', 'AkeywordController');

        Route::resource('ncats', 'NcatController');

        Route::resource('justice-kind', 'JusticeKindController');
        Route::resource('judgment-code', 'JudgmentCodeController');
        Route::resource('court-code', 'CourtCodeController');
        Route::resource('cause-category', 'CauseCategoryController');
        Route::resource('instances', 'InstanceController');
        Route::resource('judges', 'JudgeController');

        Route::resource('mauthors', 'MauthorController');
        Route::resource('mnodetypes', 'MnodetypeController');

        Route::resource('pauthors', 'PauthorController');
        Route::resource('pauthorroles', 'PauthorroleController');
        Route::resource('pglosstypes', 'PglosstypeController');
        Route::resource('psources', 'PsourceController');
        Route::resource('pdocsubtypes', 'PdocsubtypeController');

        Route::resource('cauthors', 'CauthorController');
        Route::resource('cauthorroles', 'CauthorroleController');
        Route::resource('csources', 'CsourceController');
        Route::resource('cdocsubtypes', 'CdocsubtypeController');
    });

    Route::group(['prefix' => 'tools', 'middleware' => ['isAdmin']], function() {

        Route::resource('exportdatas', 'ExportdataController');
        Route::resource('exportvocs',  'ExportvocController');
        Route::resource('exportvocmodels', 'ExportvocmodelController');
        Route::resource('blocks', 'BlockController');
        
        Route::post('/export',    ['as'=>'export', 'uses'=>'ExportController@index']);
        Route::post('/exportvoc', ['as'=>'exportvoc', 'uses'=>'ExportController@exportvoc']);

        Route::resource('logactions', 'LogactionController');
        Route::resource('logs', 'LogController');

        Route::get('/tools',       ['as'=>'tools', 'uses'=>'GeneralController@tools']);
        Route::get('/reincrement', ['as'=>'reincrement', 'uses'=>'ToolController@reincrement']);
        Route::get('/lexinform',   ['as'=>'lexinform', 'uses'=>'ToolController@lexinform']);
        Route::get('/blocks-map',  ['as'=>'blocks-map', 'uses'=>'GeneralController@create_blocks_map']);
        Route::get('/relations',   ['as'=>'relations', 'uses'=>'ToolController@relations']);
        # страница для тестов
        Route::get('/dev',   ['as'=>'dev', 'uses'=>'ToolController@dev']);
        Route::get('/link',  ['as'=>'link','uses'=>'ToolController@link']);
        Route::get('/toc',   ['as'=>'toc', 'uses'=>'ToolController@toc']);
        # страница для RADA BOT
        Route::get('/radabot',   ['as'=>'radabot', 'uses'=>'ToolController@radabot']);
        Route::resource('ractions', 'RactionController', ['except' => 'show']);

        Route::get('rbotstatuses/datatable',    ['as'=>'rbotstatuses.datatable','uses'=>'RbotstatusController@datatable']);
        Route::post('rbotstatuses/datatable',    ['as'=>'rbotstatuses.datatable','uses'=>'RbotstatusController@datatable']);
        Route::resource('rbotstatuses', 'RbotstatusController', ['except' => 'show']);
    });

    Route::match(['get', 'post'],'/account',    ['as'=>'account', 'uses'=>'GeneralController@account']);

});

Route::post( '/logout', ['as'=>'logout', 'uses'=>'GeneralController@logout']);

Route::get('/',    ['as'=>'home', 'uses'=>'GeneralController@index']);

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{

    protected $connection= 'perseus';
    //protected $primaryKey = ['nro', 'version_id', 'fragment_id'];
    protected $primaryKey = 'nro';
    protected $table = 'documents';

    const CREATED_AT = 'last_modified_date';
    const UPDATED_AT = 'last_modified_date';




}

app/Jur.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jur extends Model
{

    /***
     *
     * Отображение количества документов
     *
     ***/
    static public function doccount()
    {
        return Jur::count();
    }
}

app/Http/Controllers/Documents/ActController.php
<?php

namespace App\Http\Controllers\Documents;

use App\Act;
use App\Actversion;
use App\Type;
use App\Asubact;
use App\Publisher;
use App\Akeyword;
use App\Source;

use App\Http\Requests\StoreActRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ActController extends Controller
{
    public function __construct() {
        parent::__construct();
        $this->data['icon'] = 'icon-law';
        $this->data['title'] = trans('cms.doc-act');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => route('acts.index')]);
        $this->data['trash'] = Act::where('trash','=',1)->count();
        $this->data['trash-route'] = route('act-trash');
    }

    public function index(Request $request)
    {
        $types = Type::pluck('name','id')->prepend('',0);

        $where = [['trash','=',0]];
            if ($request->sid)  { $where[]=['id','=', $request->sid]; }
            if ($request->sname)  { $where[]=['name','like', '%'.$request->sname.'%']; }
            if ($request->snumber)  { $where[]=['number','like', '%'.$request->snumber.'%']; }
            if ($request->stype)  { $where[]=['atype_id','=', $request->stype]; }
            if ($request->sexport==1)  { $where[]=['export','=', false]; }
            if ($request->sexport==2)  { $where[]=['export','=', true]; }
        $models = Act::where($where)->orderby('id', 'desc')->paginate(20);

        return view('Documents.Act.index', [
                'types' => $types,
                'models' => $models,
                'pagination_add' => $request->input(),
                'data' => $this->data,
            ]);
    }

    public function create()
    {
        $this->data['subtitle'] = 'Создание';
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        $types = Type::pluck('name','id')->prepend('',0);
        $asubacts = Asubact::pluck('name','id')->prepend('',0);
        $publishers = Publisher::get();
        $sources = Source::pluck('name','id');
        $akeywords = Akeyword::orderby('name')->pluck('name','id');
        return view('Documents.Act.create', [
                'types' => $types,
                'asubacts' => $asubacts,
                'publishers' => $publishers,
                'sources' => $sources,
                'akeywords' => $akeywords,
                'data' => $this->data,
            ]);
    }

    public function store(StoreActRequest $request)
    {
        $model = new Act;
        $model->name = $request->name;
        $model->atype_id = $request->atype_id;
        $model->number = $request->number;
        $model->asubact_id = $request->asubact_id;
        $model->date_acc = $request->date_acc;
        $model->date_force = $request->date_force;
        $model->reestr_code = $request->reestr_code;
        $model->reestr_date = $request->reestr_date;
        $model->reg_date = $request->reg_date;
        $model->reg_number = $request->reg_number;
        $model->finisher_id = $request->finisher_id ? $request->finisher_id : 0;
        $model->finish_date = $request->finish_date;
        $model->export = $request->export ? $request->export : false;
        $model->save();
        $model->nro = $model->id + 16777216 * $model->asubact_id;
        $model->save();
        Auth::user()->log($request->ip(), 1001, $model->id);

        $submodel = new Actversion;
        $submodel->act_id = $model->id;
        $submodel->date_acc = $model->date_acc;
        $submodel->modifier_id = 0;
        $submodel->format = 1;
        $submodel->content = $request->content ? $request->content : '';
        $submodel->save();
        Auth::user()->log($request->ip(), 1011, $submodel->id);

        $model->publishers()->sync($request->publishers);
        $model->sync_sources($request->sources);
        $model->sync_keywords($request->keywords);

        return redirect()->route('acts.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
        $model = Act::findOrFail($id);
        $this->data['title'] = $model->atype->name . ' ' . $model->number;
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => "#"]);
        return view('Documents.Act.show', [
                'model'=>$model,
                'data' => $this->data,
            ]);
    }

    public function edit($id)
    {
        $model = Act::findOrFail($id);
        $this->data['subtitle'] = $model->atype->name . ' ' . $model->number . ' (редактирование)';
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);
        $types = Type::pluck('name','id')->prepend('',0);
        $asubacts = Asubact::pluck('name','id')->prepend('',0);
        $publishers = Publisher::get();
        $sources = Source::pluck('name','id');
        $akeywords = Akeyword::orderby('name')->pluck('name','id');

        return view('Documents.Act.edit', [
                'model'=>$model,
                'types' => $types,
                'asubacts' => $asubacts,
                'publishers' => $publishers,
                'sources' => $sources,
                'akeywords' => $akeywords,
                'data' => $this->data,
            ]);
    }

    public function update(StoreActRequest $request, $id)
    {
        $model = Act::findOrFail($id);
        $model->name = $request->name;
        $model->atype_id = $request->atype_id;
        $model->number = $request->number;
        $model->asubact_id = $request->asubact_id;
        $model->date_acc = $request->date_acc;
        $model->date_force = $request->date_force;
        $model->reestr_code = $request->reestr_code;
        $model->reestr_date = $request->reestr_date;
        $model->reg_date = $request->reg_date;
        $model->reg_number = $request->reg_number;
        $model->finisher_id = $request->finisher_id ? $request->finisher_id : 0;
        $model->finish_date = $request->finish_date;
        $model->export = $request->export ? $request->export : false;
        $model->nro = $model->id + 16777216 * $model->asubact_id;
        $model->save();
        Auth::user()->log($request->ip(), 1002, $model->id);

        $model->publishers()->sync($request->publishers);
        $model->sync_sources($request->sources);
        $model->sync_keywords($request->keywords);

        return redirect()->route('acts.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        if (!isset($request->_action)){
            $model = Act::findOrFail($id);
            $model->trash = 1;
            $model->save();
            Auth::user()->log($request->ip(), 1003, $model->id);
            return redirect(route('acts.index'))->with('error_message', trans('cms.alert-trash', ['name' => $model->name]));
        } else {
            if ($request->_action == 'RESTORE'){
                $model = Act::findOrFail($id);
                $model->trash = 0;
                $model->save();
                Auth::user()->log($request->ip(), 1004, $model->id);
                return redirect(route('act-trash'))->with('flash_message', trans('cms.alert-restore', ['name' => $model->name]));
            }
            if ($request->_action == 'DELETE'){
                $model = Act::findOrFail($id);
                $model->delete();
                Auth::user()->log($request->ip(), 1005, $model->id);
                return redirect(route('act-trash'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
            }
        }
    }


    /*
     * Корзина
     */

    public function trash(Request $request)
    {
        $this->data['icon'] = 'icon-trash';
        $this->data['subtitle'] = trans('cms.trash');
        array_push($this->data['breadcrumbs'] , ["title" => $this->data['subtitle'],"url" => "#"]);

        $types = Type::pluck('name','id')->prepend('',0);

        $where = [['trash','=',1]];
            if ($request->sid)  { $where[]=['id','=', $request->sid]; }
            if ($request->sname)  { $where[]=['name','like', '%'.$request->sname.'%']; }
            if ($request->snumber)  { $where[]=['number','like', '%'.$request->snumber.'%']; }
            if ($request->stype)  { $where[]=['atype_id','=', $request->stype]; }
        $models = Act::where($where)->orderby('id', 'desc')->paginate(20);

        return view('Documents.Act.trash', [
                'types' => $types,
                'models' => $models,
                'pagination_add' => $request->input(),
                'data' => $this->data,
            ]);
    }

}

resources/views/Documents/Jur/_index.blade.php
@extends('layouts.layout')


@section('content')

    <div class="card mb-3">
        <div class="card-header">{{trans('main.permissions')}}
            @include('layouts.minimize')
        </div>
        <div class="card-body">
                    <table class="table table-striped table-hover">
                        <thead class="thead-dark table-bordered">
                            <tr>
                                <th>{{trans('table.permissions')}}</th>
                                <th>{{trans('table.actions')}}</th>
                            </tr>
                            <tr>
                                {!! Form::open(['method' => 'GET', 'route' => ['jurs.index'] ]) !!}
                                    <th>{{ Form::text('sname', null, array('class' => 'form-control form-control-sm')) }}</th>
                                    <th><button class="btn btn-sm btn-filter btn-primary" title="{{trans('buttons.get-filters')}}"><i class="fa fa-fw fa-filter"></i></button></th>
                                {!! Form::close() !!}
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($models as $model)
                            <tr>
                                <td>{{ $model->name }}</td> 
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('jurs.edit', $model->id) }}" class="btn btn-info btn-sm" title="{{trans('buttons.edit')}}"><i class="fa fa-pencil fa-fw"></i></a>
                                        <a href="{{route('jurs.destroy', $model->id)}}" class="btn btn-danger btn-sm btn-remove" data-toggle="modal" data-target="#removeModal" title="{{trans('buttons.delete')}}"><i class="fa fa-trash-o fa-fw"></i></a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    {{ $models->appends($pagination_add)->links() }}

                    <a href="{{ route('jurs.create') }}" class="btn btn-success">{{trans('buttons.append')}}</a>
        </div>
        <div class="card-footer small text-muted font-italic text-right">{{trans('table.updated',['date' => date("d.m.Y"), 'time' => date("H:i")])}}</div>
    </div>

@endsection

resources/views/Documents/Jur/index.blade.php
@extends('layouts.layout')

@section('content')
    <div class="card mb-3">
        <div class="card-header bg-dark text-white">Категорії справ</div>
        <div class="card-body bg-light">
                    <table class="table table-striped table-hover small">
                        <thead class="bg-secondary text-white table-bordered">
                            <tr>
                                <th>{{trans('table.key')}}</th>
                                <th>{{trans('table.num')}}</th>
                                <th>{{trans('table.adjudication_date')}}</th>
                                <th>{{trans('table.justice_kind')}}</th>
                                <th>{{trans('table.judgment_code')}}</th>
                                <th>{{trans('table.court_code')}}</th>
                                <th>{{trans('table.judge')}}</th>
                                <th>{{trans('table.actions')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($models as $model)
                            <tr>
                                <td class="text-center">{{ $model->id }}</td>
                                <td>{{ $model->cause_num }}</td>
                                <td>{{ substr($model->adjudication_date,0,10) }}</td>
                                <td>{{ $model->justice_kind_name }}</td>
                                <td>{{ $model->judgment_code_name }}</td>
                                <td>{{ $model->court_code_id }}</td>
                                <td>{{ $model->judge }}</td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <a href="{{ route('jurs.show', $model->id) }}" class="btn btn-info btn-sm" title="{{trans('buttons.show')}}"><i class="fa fa-eye fa-fw"></i></a>
                                        <a href="{{ route('jurs.edit', $model->id) }}" class="btn btn-info btn-sm" title="{{trans('buttons.edit')}}"><i class="fa fa-pencil fa-fw"></i></a>
                                        <a href="{{route('jurs.destroy', $model->id)}}" class="btn btn-danger btn-sm btn-remove" data-toggle="modal" data-target="#removeModal" title="{{trans('buttons.delete')}}"><i class="fa fa-trash-o fa-fw"></i></a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    {{ $models->links() }}

                    <a href="{{ route('cause-category.create') }}" class="btn btn-primary">{{trans('buttons.append')}}</a>

        </div>
        <div class="card-footer small text-muted font-italic text-right bg-dark">{{trans('table.updated',['date' => date("d.m.Y"), 'time' => date("H:i")])}}</div>
    </div>

@endsection

resources/views/Documents/Jur/show.blade.php
@extends('layouts.layout')

@section('content')
    <div class="card mb-3">
        <div class="card-header bg-dark text-white">{{$model->cause_num}}</div>
        <div class="card-body bg-light" style="white-space: pre-wrap;">{{$model->text}}</div>
        <div class="card-footer small text-muted font-italic text-right bg-dark">{{trans('table.updated',['date' => date("d.m.Y"), 'time' => date("H:i")])}}</div>
    </div>

@endsection